# Rename this file to config.yml.

appname: "Math Time"
layout: "main"
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  DBIC:
    math_problems:
      schema_class: MathSheets::Schema
      dsn: dbi:SQLite:dbname=/path/to/math.db

email_alerts:
  from: 'mathsheets@foo.com'
  to: 'mathcoach@foo.com'

msgs:
  leila:
    1: 'Great job! You are on your way to becoming a math genius!'
    3: 'Your reward is 1 candy from 7-11!'
