# Rename this file to config.yml
# Make sure to update the plugins->DBIC->dsn value to point to your database.
# See https://metacpan.org/module/Dancer::Plugin::Email for documentation
# on updating the email settings, if necessary.

appname: "MathSheets"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
serializer: JSON
session: YAML

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    anycase:   0

plugins:
  DBIC:
    math_problems:
      schema_class: MathSheets::Schema
      dsn: dbi:SQLite:dbname=/path/to/math.db
  Email:
    headers:
      from: 'noreply@yourdomain.com'
    transport:
      Sendmail:
        sendmail: '/usr/sbin/sendmail'

# These are the probabilities of winning powerups in percentages. In this
# example, there is a 10% chance of winning a normal Bomb and a 5% chance
# of winning a Super Bomb, per problem.
powerups:
  1:
    probability: 10
  2:
    probability: 5
