appname: "MathSheets"
layout: "main"
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    DBIC:
        math_problems:
            schema_class: MathSheets::Schema
            dsn: dbi:SQLite:dbname=/home/naveed/projects/MathSheets/data/math.db
